<?php
namespace DataGridTest\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-17 at 11:53:23.
 */
class ArrayObject extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \DataGrid\Adapter\ArrayObject
     */
    protected $object;

    /**
     * @var array
     */
    protected $adaptable1 = array(
        array('user' => 'widmogrod'),
        array('user' => 'widmogrod2'),
        array('user' => 'widmogrod3'),
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \DataGrid\Adapter\ArrayObject($this->adaptable1);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testInstanceOf()
    {
        $this->assertInstanceOf('DataGrid\Adapter\ArrayObject', $this->object);
    }

    public function testAdaptable()
    {
        $this->assertEquals($this->adaptable1, $this->object->getAdaptable());
    }

    public function testToArray()
    {
        $this->assertEquals($this->adaptable1, $this->object->toArray());
    }

    public function testFetchData() {
        $this->assertNull($this->object->fetchData());
    }
}
