<?php
namespace DataGridTest;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-17 at 11:53:23.
 */
class DataGrid extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \DataGrid\DataGrid
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new \DataGrid\DataGrid();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers DataGrid\DataGrid::getAdapter
     * @expectedException \DataGrid\Exception\InvalidArgumentException
     */
    public function testGetAdapter()
    {
        $this->object->getAdapter();
    }

    /**
     * @covers DataGrid\DataGrid::setRenderer
     */
    public function testSetRenderer()
    {
        $this->object->setRenderer($this->getMock('DataGrid\Renderer\RendererInterface'));
    }

    /**
     * @covers DataGrid\DataGrid::getRenderer
     * @expectedException \DataGrid\Exception\InvalidArgumentException
     */
    public function testGetRenderer()
    {
        $this->object->getRenderer();
    }

    /**
     * @covers DataGrid\DataGrid::toArray
     * @todo   Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DataGrid\DataGrid::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DataGrid\DataGrid::setSpecialColumn
     * @todo   Implement testSetSpecialColumn().
     */
    public function testSetSpecialColumn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DataGrid\DataGrid::setSpecialColumns
     * @todo   Implement testSetSpecialColumns().
     */
    public function testSetSpecialColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DataGrid\DataGrid::getSpecialColumns
     * @todo   Implement testGetSpecialColumns().
     */
    public function testGetSpecialColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DataGrid\DataGrid::getSpecialColumnsByType
     * @todo   Implement testGetSpecialColumnsByType().
     */
    public function testGetSpecialColumnsByType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
